### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by UnixJunkie** [coq-contribs/finger-tree#1]
I would be interested in the ocaml code that can
be extracted from this.

I am not a Coq user...

```
File "./StringInterface.v", line 7, characters 0-49:
Warning: Notation "_ ~= _" was already used. [notation-overridden,parsing]
File "./StringInterface.v", line 21, characters 2-14:
Warning: Notation "_ ~= _" was already used. [notation-overridden,parsing]
File "./StringInterface.v", line 32, characters 11-20:
Error:
Syntax error: 'Type' or 'Types' expected after 'Implicit' (in [vernac:gallina_ext]).
```

**Comment by ybertot** [comment]
I checked, the most recent version of Coq for which the current version compiles is coq version 8.7.  If you run the compilation with that version of Coq, you will be able to obtain the extracted code.

**Comment by UnixJunkie** [comment]
Thanks a lot for having looked into this!
I am saddened to see that Coq doesn't preserve backward compatibility though.
